version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: blackcandle-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --appendfsync everysec
    networks:
      - blackcandle-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:

networks:
  blackcandle-net:
    driver: bridge
